language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: "Tests"
      name: "Tests without proxy"
      script: npm run test
    - name: "Tests with proxy"
      before_script:
        - npm install -g anyproxy
        - nohup anyproxy --port 8001 &
        - ANYPROXY_PID=$!
      script:
        - ./node_modules/.bin/mocha --exit tests/proxy_tests/*.js --require @babel/register
      after_script:
        - kill $ANYPROXY_PID


cache:
  npm: true
  directories:
    - node_modules

